# Generated by Django 4.2.7 on 2023-12-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField()),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='Category.categorymodel')),
            ],
        ),
    ]
