# Generated by Django 4.2.7 on 2023-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000, max_length=12),
        ),
    ]
